### ISSUE TITLE
Fragments not working?

### ISSUE THREAD

**Issue by timvandesteeg** [kamilkisiela/apollo-angular-introduction#1]
Generating the code and everything works like a charm. Very intuitive, good documentation, my compliments. Only thing is that I can't seem to get fragments working. 

Do you happen to have an example of a query using a fragment? Keep getting the error: 
Unknown fragment "MyFragment"

It does not seem to get send along with the request? 

My bad: duplicate of https://github.com/dotansimha/graphql-code-generator/issues/528. 
Closing this issue.

**Comment by kamilkisiela** [comment]
Hi :)

Actually, yes I have! Check out this repo https://github.com/kamilkisiela/apollo-angular-services
